version: "3.9"

services:
  web1:
    build:
      context: ./web1
    container_name: web1
    networks:
      - lbnet

  web2:
    build:
      context: ./web2
    container_name: web2
    networks:
      - lbnet

  lb:
    image: haproxy:latest
    container_name: lb
    ports:
      - "8080:80"
      - "8404:8404"  # <-- stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - web1
      - web2
    networks:
      - lbnet
      
networks:
  lbnet:
    driver: bridge
