services:
  web:
    build:
      context: ./web
    networks:
      - lbnet
    volumes:
      - ./logs/web_logs:/var/log/nginx


  haproxy:
    build:
      context: ./haproxy
    container_name: haproxy
    ports:
      - "8080:80"
      - "8404:8404"  # <-- stats page
    depends_on:
      - web
    networks:
      - lbnet

networks:
  lbnet:
    driver: bridge